version: '3.8'

services:
  chat-backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGINS=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  chat-frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${BACKEND_URL}/api
      - VITE_SOCKET_URL=${BACKEND_URL}
    depends_on:
      - chat-backend
    restart: unless-stopped
